### ISSUE TITLE
Feature Request: Request to add mark to do as done option

### ISSUE THREAD

**Issue by Prathamesh0901** [CSI-DMCE-2024/Note-App-Hacktoberfest2024#11]
As any standard todo app this app should have a mark todo as done option.
I am open to work on this.

**Comment by udaythakare** [comment]
I am open to work on this feature.

**Comment by Parth-pawar-zip** [comment]
hey leads i want to work on this issue

**Comment by DeadInsane5** [comment]
Hey leads, can I work on this?
