### ISSUE TITLE
Dark Mode/Light Mode Toggle

### ISSUE THREAD

**Issue by syedmaazsaeed** [CSI-DMCE-2024/Note-App-Hacktoberfest2024#23]
Add a button to toggle between dark mode and light mode. This feature will improve the user experience for users who prefer different visual themes.

I would like to contribute this project to the Hacktoberfest repository.

Assign me to the repository so I can start working on it. Once assigned, I will fork the repo, push my code, and submit a pull request for your review.

**Comment by YashBawari18** [comment]
Hello maintainers, I would like to work on this issue, Kindly Assign me...
