### ISSUE TITLE
Add 404 Page 

### ISSUE THREAD

**Issue by varad177** [CSI-DMCE-2024/Note-App-Hacktoberfest2024#3]
Add The Page not found page, i.e (404) Page

**Comment by Tony-ArtZ** [comment]
Can I work on this ?

**Comment by uzefaqureshi06** [comment]
can you assign this to me I will work on it

**Comment by Tony-ArtZ** [comment]
> can you assign this to me I will work on it

Sorry, I have already created a PR for this, work is done

**Comment by Aditya-jambhale** [comment]
I am interested to work on this issue

**Comment by varad177** [comment]
> > can you assign this to me I will work on it
> 
> Sorry, I have already created a PR for this, work is done

I didn't assign you this issue

**Comment by varad177** [comment]
> I am interested to work on this issue

Go For it

**Comment by Tony-ArtZ** [comment]
> > > can you assign this to me I will work on it
> > 
> > 
> > Sorry, I have already created a PR for this, work is done
> 
> I didn't assign you this issue

You had assigned no one

**Comment by udaythakare** [comment]
can i work on this issue??

**Comment by DeadInsane5** [comment]
Hey leads, can I work on this?
