### ISSUE TITLE
Improve the nav bar in mobile view

### ISSUE THREAD

**Issue by varad177** [CSI-DMCE-2024/Note-App-Hacktoberfest2024#5]
Improved the nav bar in mobile view

mobile view 
![image](https://github.com/user-attachments/assets/b92638b3-acfb-4956-8ff5-6806793500ec)

**Comment by Tony-ArtZ** [comment]
I would like to work on this please assign me this

**Comment by uzefaqureshi06** [comment]
can you assign this to me I will work on it I will make my best

**Comment by Tony-ArtZ** [comment]
> can you assign this to me I will work on it I will make my best

Sorry, I have already created a PR for this

**Comment by DeadInsane5** [comment]
Hey leads, can I work on this?

**Comment by varad177** [comment]
> Hey leads, can I work on this?

@DeadInsane5 , complete it asap

**Comment by DeadInsane5** [comment]
> > Hey leads, can I work on this?
> 
> @DeadInsane5 , complete it asap

Issue is fixed by me and I've created a PR, kindly request you to review the PR
Thanks in advance
