### ISSUE TITLE
 hover effect to cards

### ISSUE THREAD

**Issue by varad177** [CSI-DMCE-2024/Note-App-Hacktoberfest2024#7]
Add  hover effect to NOTE cards

**Comment by bulutyerli** [comment]
can you assign this to me

**Comment by uzefaqureshi06** [comment]
can you assign this to me I will work on it

**Comment by uzefaqureshi06** [comment]
bro what do you mean

**Comment by DeadInsane5** [comment]
Hey leads, can I work on this?

**Comment by tghosh294** [comment]
I can work on this

**Comment by paraoxxx6969** [comment]
**Hello maintainer can i work on this**

**Comment by Khanvilkarshravani27** [comment]
Hello Maintainer , Can I work on this issue?

**Comment by Hatykuxordik** [comment]
Hi! I'd love to contribute by adding a hover effect to the NOTE cards. Could you please assign this issue to me? Thanks!

**Comment by DeadInsane5** [comment]
Hi maintainers, can I work on this?

**Comment by mayureshh27** [comment]
> **Hello maintainer can i work on this**

@paraoxxx6969 
Gor fot it and try to complete asap

**Comment by mayureshh27** [comment]
> Hi maintainers, can I work on this?

Start Working and complete it asap 24hr time

**Comment by DeadInsane5** [comment]
> > Hi maintainers, can I work on this?
> 
> Start Working and complete it asap 24hr time

Issue is fixed by me and I've created a PR, kindly request you to review the PR
Thanks in advance
